### ISSUE TITLE
questions about Xvesa

### ISSUE THREAD

**Issue by stefan11111** [tinycorelinux/tinyx#10]
Hi.

Tinyx has the Xfbdev and Xvesa X servers.
Xfbdev works flawlessly.
Xvesa refuses to start
```
                        if (!strcmp("x86_64", info.machine)) {
                                ErrorF("Xvesa is not 64-bit compatible.\n");
                                exit(1);
                        }
```
I am on an x86_64 machine.

I tried patching this out and running the test command:
```
# Xvesa -listmodes
```
which fails like so:
```
# Xvesa -listmodes
Unexpected result code 0xFFFFFFFF from vm86
eax=0x00004F00 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
esi=0x00000000 edi=0x00000000 ebp=0x00000000
eip=0x000017EA esp=0x00000FFA eflags=0x00003200
cs=0xC000      ds=0x0000      es=0x1101      fs=0x0000      gs=0x0000
 9E 58 66 5F 5E 5B C3 ->52 50 BA CA 03 EC FE C0
vm86 failed (errno 1)
Unexpected result code 0xFFFFFFFF from vm86
eax=0x00004F00 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
esi=0x00000000 edi=0x00000000 ebp=0x00000000
eip=0x000017EA esp=0x00000FFA eflags=0x00003200
cs=0xC000      ds=0x0000      es=0x1101      fs=0x0000      gs=0x0000
 9E 58 66 5F 5E 5B C3 ->52 50 BA CA 03 EC FE C0
vm86 failed (errno 1)
0x0013: 320x200x8 (vga compatible) PseudoColor
```
I then tried to build tinyx as a 32-bit executable, by passing:
```
CFLAGS="-m32 -O3 -flto -pipe -march=native"
```
```
# file /usr/bin/Xvesa
/usr/bin/Xvesa: setuid ELF 32-bit LSB pie executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 3.2.0, stripped
```
However, this also fails like the 64-bit executable:
```
# Xvesa -listmodes
Unexpected result code 0xFFFFFFFF from vm86
eax=0x00004F00 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
esi=0x00000000 edi=0x00000000 ebp=0x00000000
eip=0x000017EA esp=0x00000FFA eflags=0x00003200
cs=0xC000      ds=0x0000      es=0x1101      fs=0x0000      gs=0x0000
 9E 58 66 5F 5E 5B C3 ->52 50 BA CA 03 EC FE C0
vm86 failed (errno 38)
Unexpected result code 0xFFFFFFFF from vm86
eax=0x00004F00 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
esi=0x00000000 edi=0x00000000 ebp=0x00000000
eip=0x000017EA esp=0x00000FFA eflags=0x00003200
cs=0xC000      ds=0x0000      es=0x1101      fs=0x0000      gs=0x0000
 9E 58 66 5F 5E 5B C3 ->52 50 BA CA 03 EC FE C0
vm86 failed (errno 38)
0x0013: 320x200x8 (vga compatible) PseudoColor
```
And at this point, I decided to ask here.
Why does this happen?
Is there a way around this? what do you do to get around this in tinycorelinux?
On what platforms does this happen? 64-bit anything, including arm and other arches? just x86_64?

**Comment by rofl0r** [comment]
isn't vm86 some ancient low-level instruction that shouldn't be used anymore ?

**Comment by stefan11111** [comment]
Took a closer look at the code.
Here seems to be the holdup:
```
static int vm86old(struct vm86_struct *vm)
{
        int res = -1;
#ifndef __x86_64__
        asm volatile ("pushl %%ebx\n\t"
                      "movl %2, %%ebx\n\t"
                      "movl %1,%%eax\n\t"
                      "int $0x80\n\t"
                      "popl %%ebx":"=a" (res):"n"(113), "r"(vm));
#endif
        if (res < 0) {
                errno = -res;
                res = -1;
        } else
                errno = 0;
        return res;
}
```
It looks to me like the above code calls syscall 113, passing it a pointer to a struct vm86_struct, storing the result in res.
According to  /usr/include/asm/unistd_x32.h, syscall 113 is setreuid:
```
#define __NR_setreuid (__X32_SYSCALL_BIT + 113)
```
However, setreuid takes 2 ints, from man 2 setreuid:
```
int setreuid(uid_t ruid, uid_t euid);
```
And also setreuid has a libc wrapper, so there should be no need to use inline assembly for this.
Furthermore, trying to port the assembly to x86_64 didn't work:
```
diff --git a/kdrive/vesa/vm86.c b/kdrive/vesa/vm86.c
index 26ecd74..1706175 100644
--- a/kdrive/vesa/vm86.c
+++ b/kdrive/vesa/vm86.c
@@ -737,14 +737,22 @@ void Vm86ReleaseMemory(Vm86InfoPtr vi, int mark)

 static int vm86old(struct vm86_struct *vm)
 {
-       int res = -1;
 #ifndef __x86_64__
+       int res = -1;
        asm volatile ("pushl %%ebx\n\t"
                      "movl %2, %%ebx\n\t"
                      "movl %1,%%eax\n\t"
                      "int $0x80\n\t"
                      "popl %%ebx":"=a" (res):"n"(113), "r"(vm));
+#else
+       long long res = -1;
+       asm volatile ("pushq %%rbx\n\t"
+                    "movq %2, %%rbx\n\t"
+                    "movl %1,%%eax\n\t"
+                    "syscall\n\t"
+                    "popq %%rbx":"=a" (res):"n"(113), "r"(vm));
 #endif
+
        if (res < 0) {
                errno = -res;
                res = -1;
```
And also, even if setreuid didn't have a libc wrapper, there is always the libc function syscall(), so even then inline assembly wouldn't be needed.

Surely I am missing something, as there is no way that this is calling actually calling setreuid, with wrong parameters.
Could someone point out what I'm missing?

**Comment by clbr** [comment]
- vesa only exists on x86, so trying to use it on arm would be pointless (vesa bios - arm has no bios)
- on TC we only ship Xvesa on 32-bit x86
- it uses those bios calls, which only work on x86. The xf86-video-vesa driver works around this with a vm86 emulator IIRC. That has never been adapted to Xvesa, and we haven't bothered either, since x86_64 usually wants accelerated drivers, or at least the full LCD resolution which Xfbdev gives. The vesa modes may not even include 1920x1080, and a selection of lower modes is not very useful on a LCD

**Comment by stefan11111** [comment]
Found a copy of my old message. Posting it again.
@clbr
I see, so TC doesn't have a solution for this either.

I tried simply faking the success of vm86old, which gave me some output:
```
# Xvesa -listmodes
Int 10h (0x4F00) failed: 0x4F00 (unknown error)
Int 10h (0x4F00) failed: 0x4F00 (unknown error)
0x0013: 320x200x8 (vga compatible) PseudoColor
```
And running Xvesa did produce some output, a very small X screen at the top of my monitor, duplicated along the length of my monitor.
The X screen was my actual X setup, and I could even open a browser in that tiny window.

I guess Xvesa just used whatever mode the video card was in, and that happened to be it.

This is how I faked the success of vm86old:
```
diff --git a/kdrive/vesa/vm86.c b/kdrive/vesa/vm86.c
index 26ecd74..4b8817f 100644
--- a/kdrive/vesa/vm86.c
+++ b/kdrive/vesa/vm86.c
@@ -737,13 +737,16 @@ void Vm86ReleaseMemory(Vm86InfoPtr vi, int mark)

 static int vm86old(struct vm86_struct *vm)
 {
-       int res = -1;
+       int res = VM86_INTx | 0xFF00;
 #ifndef __x86_64__
        asm volatile ("pushl %%ebx\n\t"
                      "movl %2, %%ebx\n\t"
                      "movl %1,%%eax\n\t"
                      "int $0x80\n\t"
                      "popl %%ebx":"=a" (res):"n"(113), "r"(vm));
+#if 0
+       res = syscall(113, vm);
+#endif
 #endif
        if (res < 0) {
                errno = -res;
@@ -752,3 +755,4 @@ static int vm86old(struct vm86_struct *vm)
                errno = 0;
        return res;
 }
+
```
I also found this old project, which claims that it was once able to implement the vm86 syscall on x86_64 linux:
https://v86-64.sourceforge.net/

Does anyone know the reason why this syscall wasn't implemented on 64-bit linux?

On another note, is there some way to prevent building Xvesa via options passed to ./configure or make?
