### ISSUE TITLE
Running tinyx on top of tty1-tty6

### ISSUE THREAD

**Issue by stefan11111** [tinycorelinux/tinyx#15]
I tried running Xfbdev on tty's 1-6.
On these tty's I have an agetty launched by init that is set to respawn when killed.
When running Xfbdev on top of tty's 1-6, input is broken.
Xfbdev doesn't register all the input, but does register some.
If I, for example, try to run Xfbdev from tty1 and tell it to run on tty2, I sometimes can get it to go back to tty1 by repeatedly mashing CTRL + ALT + F1.

From what I see, the problem is that Xfbdev fails to get all the input from the tty I tell it to run on.

Xorg doesn't have this problem.

I found this commit that I tried to backport: https://lists.freedesktop.org/archives/xorg-devel/2012-January/028415.html

Sadly, this didn't work.
Using K_OFF instead of K_MEDIUMRAW even broke input when running on free tty's, like tty7 and above.
Using K_RAW doesn't fix the issue either, the results I sow with is are the same as what I saw with K_MEDIUMRAW

Do you have any ideas how I might go and try to fix this?

**Comment by clbr** [comment]
Don't try to run it on a tty something else is running on? Even with
Xorg that's not recommended.
