### ISSUE TITLE
build error on debian jessie i686

### ISSUE THREAD

**Issue by michele13** [tinycorelinux/tinyx#2]
I get this error when I try to build tinyx and run `make` in Debian Jessie 

`
make[2]: Entering directory '/home/michele/tmp/tinyx/kdrive/fbdev'
gcc -flto -fuse-linker-plugin -march=i486 -mtune=i686 -Os -pipe -DHAVE_CONFIG_H -I. -I../../include  -I../../kdrive/src -I../../miext/damage -I../../miext/shadow -I../../Xext -I../../fb -I../../mi -I../../kdrive/linux -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/include/freetype2 -I../../include -I../../include -I../../Xext -I../../damageext -I../../xfixes -I../../mi -I../../miext/shadow  -I../../miext/damage -I../../render -I../../randr -I../../fb -DHAVE_KDRIVE_CONFIG_H   -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/include/freetype2 -I../../include -I../../include -I../../Xext -I../../damageext -I../../xfixes -I../../mi -I../../miext/shadow  -I../../miext/damage -I../../render -I../../randr -I../../fb -g   -flto -fvisibility=hidden -fno-unwind-tables -fno-asynchronous-unwind-tables -Wall -MT fbdev.o -MD -MP -MF .deps/fbdev.Tpo -c -o fbdev.o fbdev.c
mv -f .deps/fbdev.Tpo .deps/fbdev.Po
rm -f libfbdev.a
ar cru libfbdev.a fbdev.o 
ar: `u' modifier ignored since `D' is the default (see `U')
ar: fbdev.o: plugin needed to handle lto object
ranlib libfbdev.a
ranlib: fbdev.o: plugin needed to handle lto object
gcc -flto -fuse-linker-plugin -march=i486 -mtune=i686 -Os -pipe -DHAVE_CONFIG_H -I. -I../../include  -I../../kdrive/src -I../../miext/damage -I../../miext/shadow -I../../Xext -I../../fb -I../../mi -I../../kdrive/linux -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/include/freetype2 -I../../include -I../../include -I../../Xext -I../../damageext -I../../xfixes -I../../mi -I../../miext/shadow  -I../../miext/damage -I../../render -I../../randr -I../../fb -DHAVE_KDRIVE_CONFIG_H   -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/include/freetype2 -I../../include -I../../include -I../../Xext -I../../damageext -I../../xfixes -I../../mi -I../../miext/shadow  -I../../miext/damage -I../../render -I../../randr -I../../fb -g   -flto -fvisibility=hidden -fno-unwind-tables -fno-asynchronous-unwind-tables -Wall -MT fbinit.o -MD -MP -MF .deps/fbinit.Tpo -c -o fbinit.o fbinit.c
mv -f .deps/fbinit.Tpo .deps/fbinit.Po
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -flto -fuse-linker-plugin -march=i486 -mtune=i686 -Os -pipe  -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/include/freetype2 -I../../include -I../../include -I../../Xext -I../../damageext -I../../xfixes -I../../mi -I../../miext/shadow  -I../../miext/damage -I../../render -I../../randr -I../../fb -g   -flto -fvisibility=hidden -fno-unwind-tables -fno-asynchronous-unwind-tables -Wall  -flto -Wl,-as-needed -Wl,-O1 -o Xfbdev fbinit.o libfbdev.a ../../dix/libdix.la ../../kdrive/src/libkdrive.a ../../kdrive/linux/liblinux.a ../../fb/libfb.la ../../mi/libmi.la ../../xfixes/libxfixes.la ../../Xext/libXext.la ../../dbe/libdbe.la ../../render/librender.la ../../randr/librandr.la ../../damageext/libdamageext.la ../../miext/damage/libdamage.la ../../miext/shadow/libshadow.la ../../os/libos.la ../../kdrive/src/libkdrivestubs.a -lXfont -lfontenc -lXdmcp  -lm                                          
libtool: link: gcc -flto -fuse-linker-plugin -march=i486 -mtune=i686 -Os -pipe -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -I/usr/include/freetype2 -I../../include -I../../include -I../../Xext -I../../damageext -I../../xfixes -I../../mi -I../../miext/shadow -I../../miext/damage -I../../render -I../../randr -I../../fb -g -flto -fvisibility=hidden -fno-unwind-tables -fno-asynchronous-unwind-tables -Wall -flto -Wl,-as-needed -Wl,-O1 -o Xfbdev fbinit.o  libfbdev.a ../../dix/.libs/libdix.a ../../kdrive/src/libkdrive.a ../../kdrive/linux/liblinux.a ../../fb/.libs/libfb.a ../../mi/.libs/libmi.a ../../xfixes/.libs/libxfixes.a ../../Xext/.libs/libXext.a ../../dbe/.libs/libdbe.a ../../render/.libs/librender.a ../../randr/.libs/librandr.a ../../damageext/.libs/libdamageext.a ../../miext/damage/.libs/libdamage.a ../../miext/shadow/.libs/libshadow.a ../../os/.libs/libos.a ../../kdrive/src/libkdrivestubs.a -lXfont -lfontenc -lXdmcp -lm
/usr/lib/gcc/i686-linux-gnu/6/../../../i386-linux-gnu/Scrt1.o: In function `_start':
(.text+0x28): undefined reference to `main'
collect2: error: ld returned 1 exit status
Makefile:451: recipe for target 'Xfbdev' failed
make[2]: *** [Xfbdev] Error 1
make[2]: Leaving directory '/home/michele/tmp/tinyx/kdrive/fbdev'
Makefile:393: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/michele/tmp/tinyx/kdrive'
Makefile:443: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

real    1m56.249s
user    1m38.008s
sys     0m9.124s
`

my configure parameters
`
CC="gcc -flto -fuse-linker-plugin -march=i486 -mtune=i686 -Os -pipe" CXX="g++ -flto -fuse-linker-plugin -march=i486 -mtune=i686 -Os -pipe -fno-exceptions -fno-rtti" ./configure --prefix=/home/michele/tinyx --disable-static --enable-install-setuid

find . -name Makefile -type f -exec sed -i 's/-O2/ /g' {} \;

make

`

**Comment by rofl0r** [comment]
remove `-flto`

**Comment by clbr** [comment]
On Mon, 29 Oct 2018 19:23:27 -0700
Michele Bucca <notifications@github.com> wrote:

> ar: fbdev.o: plugin needed to handle lto object
> ranlib: fbdev.o: plugin needed to handle lto object

Yes, rofl0r is correct. These lines mean your system is not able to
use LTO. I think that Debian is too old for it.

You may also have to edit configure.ac to remove the LTO check, in case
that Debian version has a new enough GCC but too old binutils (weird,
but possible, so mentioning).

**Comment by rofl0r** [comment]
gcc 4.5 introduced lto. it's very unlikely debian has an older gcc. what's happening here is that they don't bundle the lto linker plugins required to handle .a files that have gimple bytecode in them (which would require that OP has built all dependent libraries with the linker plugin and statically rather than dynamically, so it doesn't even make sense for him/her). so in fact, just removing `-fuse-linker-plugin` should actually be the right fix.

**Comment by michele13** [comment]
Ok all I needed to do was to change 
`find . -name Makefile -type f -exec sed -i 's/-O2/ /g' {} ;`
to
`find . -name Makefile -type f -exec sed -i 's/-O2 -flto/ /g' {} \;`
Now however I get this error

```
Unexpected result code 0xFFFFFFFF from vm86
eax=0x00004F00 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
esi=0x00000000 edi=0x00000000 ebp=0x00000000
eip=0x00000022 esp=0x00000FFA eflags=0x00003200
cs=0xC000      ds=0x0000      es=0x1101      fs=0x0000      gs=0x0000
 00 00 00 49 42 4D 00 ->9C 80 FC 0F 75 06 E8 4F
vm86 failed (errno 38)
Unexpected result code 0xFFFFFFFF from vm86
eax=0x00004F00 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
esi=0x00000000 edi=0x00000000 ebp=0x00000000
eip=0x00000022 esp=0x00000FFA eflags=0x00003200
cs=0xC000      ds=0x0000      es=0x1101      fs=0x0000      gs=0x0000
 00 00 00 49 42 4D 00 ->9C 80 FC 0F 75 06 E8 4F
vm86 failed (errno 38)
Unexpected result code 0xFFFFFFFF from vm86
eax=0x00004F03 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
esi=0x00000000 edi=0x00000000 ebp=0x00000000
eip=0x00000022 esp=0x00000FFA eflags=0x00003200
cs=0xC000      ds=0x0000      es=0x1101      fs=0x0000      gs=0x0000
 00 00 00 49 42 4D 00 ->9C 80 FC 0F 75 06 E8 4F
vm86 failed (errno 38)
Unexpected result code 0xFFFFFFFF from vm86
eax=0x00000013 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
esi=0x00000000 edi=0x00000000 ebp=0x00000000
eip=0x00000022 esp=0x00000FFA eflags=0x00003200
cs=0xC000      ds=0x0000      es=0x1101      fs=0x0000      gs=0x0000
 00 00 00 49 42 4D 00 ->9C 80 FC 0F 75 06 E8 4F
vm86 failed (errno 38)

Fatal server error:
no screens found
Segmentation fault

```

**Comment by clbr** [comment]
Your system is not compatible with Xvesa. I wonder if you have an
accelerated kernel module loaded (radeon, nouveau, etc) or other such
complication.
