### ISSUE TITLE
Question on changing file hierarchy layout? 

### ISSUE THREAD

**Issue by Shadowblitz16** [tinycorelinux/tinyx#4]
Is there a easy way to modify the filesystem hierarchy layout?
I am making my own toy linux distro and since I am already breaking compatibility with programs by making everything lua based,
I want to break the linux file hierarchy standard too.

**Comment by clbr** [comment]
You can change the various paths with configure args. Whether they're complete or source changes are also needed, I don't know.

**Comment by Shadowblitz16** [comment]
can you go into detail the wiki for tiny core linux seems to be dead.

**Comment by clbr** [comment]
What are you asking about? This is the TinyX repo, I thought you were asking about putting Xvesa in a different path.

**Comment by Shadowblitz16** [comment]
I thought this was the tinycore linux repo?
I couldn't find a repo named tiny core linux and I thought the x stood for linux

**Comment by clbr** [comment]
No. Closing.

Your question is best answered at a forum or such.
