### ISSUE TITLE
Sources won't compile on Debian 10

### ISSUE THREAD

**Issue by tlisjac** [tinycorelinux/tinyx#5]
Linking fails at the end while trying to compile the tinyx sources with the errors below. I suspect that the libxfont2 dev package (rather then libxfont) from the Debian 10 repos may introduce header changes that the earlier version lacked:

rrcrtc.c:617:19: warning: argument 1 range [18446744073709551560, 18446744073709551608] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
/usr/include/stdlib.h:539:14: note: in a call to allocation function 'malloc' declared here
 extern void *malloc (size_t __size) __THROW __attribute_malloc__ __wur;
              ^
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find abbrev number 84
/tmp/ccy36L0L.ltrans0.ltrans.o: in function `ProcessCommandLine':
<artificial>:(.text+0x8ea0): undefined reference to `ParseGlyphCachingMode'
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find abbrev number 113
/tmp/ccy36L0L.ltrans4.ltrans.o: in function `ProcXF86BigfontQueryFont':
<artificial>:(.text+0x7483): undefined reference to `_FontSetNewPrivate'
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find abbrev number 3275
/tmp/ccy36L0L.ltrans7.ltrans.o: in function `miImageText16':
<artificial>:(.text+0xa40): undefined reference to `GetGlyphs'
/usr/bin/ld: /tmp/ccy36L0L.ltrans7.ltrans.o: in function `miImageText8':
<artificial>:(.text+0xac5): undefined reference to `GetGlyphs'
/usr/bin/ld: /tmp/ccy36L0L.ltrans7.ltrans.o: in function `miPolyText16':
<artificial>:(.text+0xb51): undefined reference to `GetGlyphs'
/usr/bin/ld: /tmp/ccy36L0L.ltrans7.ltrans.o: in function `miPolyText8':
<artificial>:(.text+0xc06): undefined reference to `GetGlyphs'
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find abbrev number 105
/tmp/ccy36L0L.ltrans13.ltrans.o: in function `main':
<artificial>:(.text.startup+0x4a9): undefined reference to `InitGlyphCaching'
/usr/bin/ld: <artificial>:(.text.startup+0x540): undefined reference to `ResetFontPrivateIndex'
/usr/bin/ld: <artificial>:(.text.startup+0x1663): undefined reference to `MakeFontPatternCache'
/usr/bin/ld: <artificial>:(.text.startup+0x166f): undefined reference to `FontFileRegisterFpeFunctions'
/usr/bin/ld: <artificial>:(.text.startup+0x20ea): undefined reference to `FreeFontPatternCache'
/usr/bin/ld: <artificial>:(.text.startup+0x2bbe): undefined reference to `AllocateFontPrivateIndex'
/usr/bin/ld: /usr/bin/ld: DWARF error: offset (7537237) greater than or equal to .debug_str size (326)
/usr/bin/ld: DWARF error: offset (961807360) greater than or equal to .debug_str size (326)
/usr/bin/ld: DWARF error: offset (4189061120) greater than or equal to .debug_str size (326)
/usr/bin/ld: DWARF error: could not find abbrev number 71
/tmp/ccy36L0L.ltrans1.ltrans.o: in function `damageDamageChars':
<artificial>:(.text+0x2d7f): undefined reference to `QueryGlyphExtents'
/usr/bin/ld: /tmp/ccy36L0L.ltrans1.ltrans.o: in function `damageText':
<artificial>:(.text+0x3056): undefined reference to `GetGlyphs'
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find abbrev number 2702
/tmp/ccy36L0L.ltrans14.ltrans.o: in function `doListFontsAndAliases.lto_priv.613':
<artificial>:(.text+0x2e5a): undefined reference to `FreeFontNames'
/usr/bin/ld: <artificial>:(.text+0x2f34): undefined reference to `AddFontNamesName'
/usr/bin/ld: <artificial>:(.text+0x3152): undefined reference to `AddFontNamesName'
/usr/bin/ld: /tmp/ccy36L0L.ltrans14.ltrans.o: in function `CloseFont':
<artificial>:(.text+0x33b9): undefined reference to `RemoveCachedFontPattern'
/usr/bin/ld: /tmp/ccy36L0L.ltrans14.ltrans.o: in function `doOpenFont':
<artificial>:(.text+0x4642): undefined reference to `CacheFontPattern'
/usr/bin/ld: /tmp/ccy36L0L.ltrans14.ltrans.o: in function `OpenFont':
<artificial>:(.text+0x982c): undefined reference to `FindCachedFontPattern'
/usr/bin/ld: /tmp/ccy36L0L.ltrans14.ltrans.o: in function `SetFontPathElements':
<artificial>:(.text+0xa598): undefined reference to `EmptyFontPatternCache'
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find abbrev number 63
/tmp/ccy36L0L.ltrans15.ltrans.o: in function `ProcListFonts':
<artificial>:(.text+0x20c5): undefined reference to `MakeFontNamesRecord'
/usr/bin/ld: /tmp/ccy36L0L.ltrans15.ltrans.o: in function `ProcQueryTextExtents':
<artificial>:(.text+0x24fb): undefined reference to `QueryTextExtents'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:453: Xfbdev] Error 1
make[2]: Leaving directory '/home/user/Downloads/tinyx-1.0/kdrive/fbdev'
make[1]: *** [Makefile:393: all-recursive] Error 1
make[1]: Leaving directory '/home/user/Downloads/tinyx-1.0/kdrive'
make: *** [Makefile:443: all-recursive] Error 1

**Comment by clbr** [comment]
libxfont2 is not api or abi compatible, you do need ver 1.

**Comment by tlisjac** [comment]
Thanks for your reply and great work on this project.
Searched, but wasn't able to find anything except libxfont2 sources as the world seems to have moved to that version. Since it's the only package lacking to compile tinyx on a standard distro, would it be possible to add a link to the project page where version 1 can be found?

**Comment by clbr** [comment]
https://www.x.org/archive/individual/lib/

I'm not sure downstream README is the right place, since that's the go-to place for X lib sources. I guess Debian doesn't package it for your version anymore?

**Comment by clbr** [comment]
On second thought, added.

**Comment by tlisjac** [comment]
Working... thanks very much for the link!

**Comment by clbr** [comment]
Do you want to close this?

**Comment by tlisjac** [comment]
Sorry, thought I had closed the issue... hope it works this time.
