### ISSUE TITLE
pre generated configure script etc

### ISSUE THREAD

**Issue by hovercats** [tinycorelinux/tinyx#6]
Alot of projects release a tarball with autotools pre runned, so configure and other neccessary files is already pregenerated (some also include this in the repo instead, bypassing the need for a tarball). this is really great for users not wanting to have autotools (aswelll as perl) on their system. 
would it be possible to simply include the neccessay files, so users (including myself) no longer need autotools to?

**Comment by clbr** [comment]
Generated files should not be stored in git. As for tarballs, TinyCore being the main consumer for this project, they aren't necessary for us. So for now, we won't provide release tarballs.

**Comment by hovercats** [comment]
ok, thats a fair argument.
